### ISSUE TITLE
Installing Vagrant Cachier requires installing non-standard packages on Ubuntu 14.04 host

### ISSUE THREAD

**Issue by philipnorton42** [hashbangcode/vlad#71]
When I tried to install vagrant cachier package on Ubuntu 14.04 host, I encountered following error:

```
#!text

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.3.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.3.1'` succeeds before bundling.
```
When I tried to install it using ````gem install nokogiri -v '1.6.3.1'```` it indeed failed with:

```
#!text

ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:4:in `<main>'

```
I searched for a solution and it turned out, that I need to install it with:
````
sudo gem install nokogiri --use-system-libraries
````
but before that i had to install further packages with:
````
sudo apt-get install ruby-dev ruby-libxml libxml2-dev libxslt1-dev
````
It would be nice, if this would be mentioned in wiki, because I had to search for a while to solve this problem.

References:
https://github.com/mitchellh/vagrant/issues/3769
https://ask.openstack.org/en/question/6064/where-can-i-get-the-missing-xmlversionh-file-when-installing-keystone/
http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror

---------------------------------------
- Bitbucket: https://bitbucket.org/philipnorton42/vlad/issue/71
- Originally Reported By: [Miloš Kroulík](http://bitbucket.org/miloskroulik)
- Originally Created At: 2014-07-27T17:46:16.697

**Comment by philipnorton42** [comment]
This information now in the documentation:
http://vlad-docs.readthedocs.org/en/latest/usage/installation/
